version: '3.8'

services:
  # zookeeper:
  #   image: 'wurstmeister/zookeeper:latest'
  #   ports:
  #     - 2181:2181
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  #   networks:
  #     - main-network

  # kafka:
  #   image: 'wurstmeister/kafka:latest'
  #   ports:
  #     - 9092:9092
  #   environment:
  #     - KAFKA_BROKER_ID=1
  #     - KAFKA_LISTENERS=PLAINTEXT://:9092
  #     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
  #     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #   depends_on:
  #     - zookeeper
  #   networks:
  #     - main-network

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - api-service
      - socket-service
    networks:
      - main-network

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: sociogram
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - database-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - VITE_API_URL=http://api.localhost
      - VITE_SOCKET_URL=http://socket.localhost
    depends_on:
      - api-service
      - socket-service
    networks:
      - main-network

  api-service:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    volumes:
      - ./api-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgres://postgres:123456@postgres:5432/sociogram
      - FRONTEND_URL=http://localhost
      - JWT_SECRET=secret
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - main-network
      - database-network

  socket-service:
    build:
      context: ./socket-service
      dockerfile: Dockerfile
    volumes:
      - ./socket-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DATABASE_URL=postgres://postgres:123456@postgres:5432/sociogram
      - JWT_SECRET=secret
    depends_on:
      - postgres
    networks:
      - main-network
      - database-network

networks:
  main-network:
  database-network:
